### ISSUE TITLE
[US-01] List with activties

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#1]
As a user I want to see a list with four actvities (cards): Two for cycling and two for running.

## Description
<img width="768" alt="Bildschirmfoto 2021-10-07 um 15 29 37" src="https://user-images.githubusercontent.com/89028778/136394751-ed315a35-ae57-413d-b4a2-7802fd7ec52b.png">

## Acceptance Criteria
- [x] List should contain four activities (cards) with mock data.
- [x] Two cards should display an icon for cycling next to the title.
- [x] The other two cards should display an icon for running next to the title.

## Tasks 
- [x] Create feature branch
- [x] Build  component for activity
- [x] Build component for list with activities
- [x] Add styled-components
- [x] Add mock data for rendering and testing
- [x] Render four activities
- [x] Write test for components
- [x] Write stories for components in storybook

## Complexity
low
