### ISSUE TITLE
[US-06] Login

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#13]
As a user I  want to login into the app. 

## Acceptance Criteria
- [] A login-page with an input-field and submit button
- [] After log in the user should be redirected to the home-category
- [] After the username is deleted in local storage the user should be redirected to the login-page.

## Tasks
- [] create login component
- [] save username to local storage
- [] update routes
- [] write tests for login component
- [] write story for storybook

## Complexity
medium
