### ISSUE TITLE
[US-07] Header

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#15]
As a user I  want a header which shows if I am logged in.

## Acceptance Criteria
- [] A header 
- [] Header should greet the user by his/her name.

## Tasks
- [] create header component
- [] adjust layout to integrate header
- [] add function to display user-name

## Complexity
low
