### ISSUE TITLE
[US-08] Delete Button

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#18]
As a user I  want a button to delete single activities.

## Acceptance Criteria
- [x] Activities should have a delete button. 
- [x] Activity should be gone after clicking the delete button.

## Tasks
- [x] create button
- [x] write function to delete an activity on button click
- [x] write function to save updated data in local storage

## Complexity
medium
