### ISSUE TITLE
[US-02] Expand activity (card)

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#2]
As a user I want a button to expand the activity-card to see additional infos. On the expanded card I want the button to collapse the expanded view.

## Description

<img width="574" alt="Bildschirmfoto 2021-10-14 um 10 03 02" src="https://user-images.githubusercontent.com/89028778/137276594-c73bee50-0561-423e-9db1-468a67da6248.png">

<img width="468" alt="Bildschirmfoto 2021-10-14 um 10 03 10" src="https://user-images.githubusercontent.com/89028778/137276623-8100ca8b-0f67-4799-bfec-de66ee3e0a81.png">

## Acceptance Criteria

- [x] On button click the card should expand and show more info.
- [x] On button click the expanded card should collapse.

## Tasks

- [x] Create feature branch
- [x] Add styled-components
- [x] Add button to activity-card
- [x] Add function to expand or collapse activity-card when clicked/touched respectively button is clicked.
- [x] Write test for new feature and and add to already existing activity-card-tests.
- [x] Write button-story for storybook.

## Complexity
medium
