### ISSUE TITLE
[US-09] Search Bar

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#21]
As a user I  want a search bar, so I can search for activities by postal code and city.

## Acceptance Criteria
- [x] There should be search bar. 
- [x] When typing a postal codes or name of a city into the search field matching results should be displayed.

## Tasks
- [x] create search box
- [x] write function to search for activities
- [x] implement functionality in components

## Complexity
medium
