### ISSUE TITLE
[US-10] Styling

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#24]
As a user I  want a design, that is easy on the eyes and a suitable user experience.

## Acceptance Criteria
- [x] Matching color palette
- [x] useful UX

## Tasks
- [x] change colors 
- [x] remove more-button 
- [x] make activities expand by clicking them everywhere

## Complexity
low
