### ISSUE TITLE
[US-11] Error Note

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#25]
As a user I want an error-note when ich navigate to joined activities and the category is empty.

## Acceptance Criteria
- [x] An error note should be displayed, when the joined-category is empty

## Tasks
- [x] create component for error note
- [x] implement new component 

## Complexity
low
