### ISSUE TITLE
[US-03] Button to join an activity

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#3]
As a user I want a button on the expanded activity-card to join or withdraw from the activity.

## Description

<img width="355" alt="Bildschirmfoto 2021-10-14 um 10 31 18" src="https://user-images.githubusercontent.com/89028778/137298930-20ea3b9e-f137-40db-9467-dc4903993946.png">
<img width="340" alt="Bildschirmfoto 2021-10-14 um 10 31 58" src="https://user-images.githubusercontent.com/89028778/137298984-6c74937a-4414-4cde-af78-b590f323ee02.png">

## Acceptance criteria

- [x] There should be a button on the expanded card to join the activity.
- [x] If the button is clicked it should change its appearance, so the user can withdraw from the activity. 

## Tasks
- [x] Build button component.
- [x] Write function to switch between the state of the button. 
- [x]  Add test for button.
- [x] Write story for storybook.

## Complexity
medium
