### ISSUE TITLE
[US-04] Navigation

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#4]
As a user I want icons in the footer to navigate between "home" and "joined". When clicked the appearance of the icons should change (color, size, etc.) to indicate which page of the app is shown. When I click "joined" my joined (bookmarked) activities should display. My "joined activities" should not disappear after reloading the page.

## Description

<img width="435" alt="Bildschirmfoto 2021-10-15 um 10 55 35" src="https://user-images.githubusercontent.com/89028778/137461016-a5ccc6e6-76f2-42b8-a6a7-7037374c9b95.png">

## Acceptance Criteria
- [x] There should be icons for "home" and "joined" in the footer.
- [x] The appearance of the icons should change when active.
- [x] The joined-icon should direct to a joined-page. 
- [x] The home-icon should direct to the start-page and show all available activities.
- [x] "Joined activities" should not disappear after reloading the page.
## Tasks
- [x] Implement navigation in footer with icons for "home" and "joined".
- [x] Create function to change the state of the activities (joined or not joined)
- [x] implement local storage 
- [x] Implement routing to navigate between "home" and "joined".
- [x] Write tests if footer is rendered and icons are shown
- [x] Write test if joined-page is rendered.

## Complexity
medium - advanced
