### ISSUE TITLE
[US-05] Display joined-activities on activity-page

### ISSUE THREAD

**Issue by martinhaiss** [martinhaiss/capstone-project#5]
As a user I  want a form to create activities

## Acceptance Criteria
- [x] Icon in the footer to navigate to form
- [x] Form with input fields
- [x] Button to submit form
- [x] New created activities should appear on top of start/home
- [x] new activities should not disappear after reload
## Tasks
- [x] add icon to footer
- [x] adjust routing
- [x] add form
- [x] add function to submit form
- [x] add function to save form to and load from local storage
## Complexity
medium
